apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: watashi93-watashi93-poi-map-app-dev
  annotations:
    argocd/app-name: watashi93-watashi93-poi-map-app-dev
    backstage.io/kubernetes-id: watashi93-watashi93-poi-map-app-dev
    backstage.io/kubernetes-namespace: watashi93
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=watashi93-watashi93-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/watashi93-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/watashi93/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/watashi93/deployments/watashi93-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/watashi93-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://watashi93-poi-map-app-watashi93.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/watashi93"
  system: workshop-system-watashi93
  consumesApis:
    - gateway-api-watashi93
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-watashi93
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/watashi93"
